name: aplicacao_bancaria
description: Aplicativo bancário com CRUD utilizando API.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  http: ^0.13.5

 
  provider: ^6.0.5

  
  flutter_json_view: ^1.0.0

  flutter_form_builder: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
